### ISSUE TITLE
Gorilla model working on AI100?

### ISSUE THREAD

**Issue by willswordh** [quic/efficient-transformers#77]
Hi, is there any information that Gorilla OpenFunctions v2 will be able to run on AI100? Thanks!

**Comment by ochougul** [comment]
Hi @willswordh, Thanks for opening the issue.
You should look at the architecture of the model in the `config.json` file on `huggingface`, If the architecture is same as one of the models written here -> https://github.com/quic/efficient-transformers?tab=readme-ov-file#validated-models, you can be sure that the new model will also be supported.

In your case, the Gorilla model is based on Llama architecture which is already supported.

**Comment by ochougul** [comment]
Closing this issue, please reopen if required in future.
