### ISSUE TITLE
Token speed really slow for running Llama3 on AI 100

### ISSUE THREAD

**Issue by willswordh** [quic/efficient-transformers#78]
Hi! I was running  Llama3 8b model on AI 100, but the token speed is very slow around 6 token/s for decode. Could you help me figure out what are the possible reasons? Thanks！I am running the release/1.15 of the repo.

**Comment by ochougul** [comment]
please share the command and logs.
Also, system info with `lscpu` and Cloud AI 100 card info with `/opt/qti-aic/tools/qaic-util`

**Comment by willswordh** [comment]
@ochougul Thanks for your help! The command is 
`python -m QEfficient.cloud.infer --model_name gorilla-llm/gorilla-openfunctions-v2 --batch_size 1 --prompt_len 64 --ctx_len 4096 --num_cores 16 --device-group [0] --prompt "My name is " --mos 1 --aic_enable_depth_first`

Please see below images for logs, system info and card info 

<img width="1065" alt="Screenshot 2024-07-23 at 10 38 36 AM" src="https://github.com/user-attachments/assets/c7a2ebef-5a7f-4f62-b618-cff72bef1beb">
<img width="900" alt="Screenshot 2024-07-23 at 10 38 44 AM" src="https://github.com/user-attachments/assets/13f39d4a-a6e9-49d8-ba0e-6f2549379923">
<img width="1302" alt="Screenshot 2024-07-23 at 10 37 27 AM" src="https://github.com/user-attachments/assets/f4556718-8b18-403c-ab63-f4688c61a4b1">
<img width="1277" alt="Screenshot 2024-07-23 at 10 37 14 AM" src="https://github.com/user-attachments/assets/cffcc6dc-a8d1-4cf1-aece-1c6bfa396c83">
<img width="721" alt="Screenshot 2024-07-23 at 10 15 04 AM" src="https://github.com/user-attachments/assets/2c6cd228-ea5c-46d3-bf47-fdeb7aed986d">

**Comment by willswordh** [comment]
@ochougul There is also a weird output with dots with different models. It seems the dots covered the entire length of the context length, which is very bizarre.

<img width="1049" alt="Screenshot 2024-07-23 at 4 37 19 PM" src="https://github.com/user-attachments/assets/cbb5e0f5-133e-4c47-b902-287944463adc">

**Comment by ochougul** [comment]
Hi @willswordh , Thanks for providing the details; we were able to reproduce the performance results.
For performance improvements, you can use the `--mxfp6` flag. This flag compresses constant `MatMul weights` to `MXFP6 E2M3`, which reduces memory traffic at the expense of slightly more compute.

In the latest `release/1.16`, we have introduced another performance optimization flag, `--mxint8`. This flag compresses the KV cache to `mxint8` precision, also reducing memory traffic with a slight increase in compute requirements.

Regarding the output issue you mentioned, we did not encounter the continuous dots in the output. The output appears as expected. Please ensure you are using the correct versions of the `transformers` and `tokenizers` packages.
![image_gorilla_llm_results](https://github.com/user-attachments/assets/65bea5e3-c311-4a64-9462-07d3220a417e)

**Comment by willswordh** [comment]
@ochougul Thanks a lot!!
